// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace OrangeHrm
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// ClickCheckBoxButton - Use 'ClickCheckBoxButtonParams' to pass parameters into this method.
        /// </summary>
        public void ClickCheckBoxButton()
        {
            #region Variable Declarations
            HtmlCheckBox uIChkSelectAllCheckBox = this.UIOrangeHRMWindowsInteWindow.UIOrangeHRMDocument.UIChkSelectAllCheckBox;
            #endregion

            // Select 'chkSelectAll' check box
            uIChkSelectAllCheckBox.Checked = this.ClickCheckBoxButtonParams.UIChkSelectAllCheckBoxChecked;
        }
        
        #region Properties
        public virtual ClickCheckBoxButtonParams ClickCheckBoxButtonParams
        {
            get
            {
                if ((this.mClickCheckBoxButtonParams == null))
                {
                    this.mClickCheckBoxButtonParams = new ClickCheckBoxButtonParams();
                }
                return this.mClickCheckBoxButtonParams;
            }
        }
        
        public UIOrangeHRMWindowsInteWindow UIOrangeHRMWindowsInteWindow
        {
            get
            {
                if ((this.mUIOrangeHRMWindowsInteWindow == null))
                {
                    this.mUIOrangeHRMWindowsInteWindow = new UIOrangeHRMWindowsInteWindow();
                }
                return this.mUIOrangeHRMWindowsInteWindow;
            }
        }
        #endregion
        
        #region Fields
        private ClickCheckBoxButtonParams mClickCheckBoxButtonParams;
        
        private UIOrangeHRMWindowsInteWindow mUIOrangeHRMWindowsInteWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ClickCheckBoxButton'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class ClickCheckBoxButtonParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'chkSelectAll' check box
        /// </summary>
        public bool UIChkSelectAllCheckBoxChecked = true;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIOrangeHRMWindowsInteWindow : BrowserWindow
    {
        
        public UIOrangeHRMWindowsInteWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "OrangeHRM";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("OrangeHRM");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIOrangeHRMDocument UIOrangeHRMDocument
        {
            get
            {
                if ((this.mUIOrangeHRMDocument == null))
                {
                    this.mUIOrangeHRMDocument = new UIOrangeHRMDocument(this);
                }
                return this.mUIOrangeHRMDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIOrangeHRMDocument mUIOrangeHRMDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIOrangeHRMDocument : HtmlDocument
    {
        
        public UIOrangeHRMDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "OrangeHRM";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/index.php/admin/viewSystemUsers";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://opensource.demo.orangehrmlive.com/index.php/admin/viewSystemUsers";
            this.WindowTitles.Add("OrangeHRM");
            #endregion
        }
        
        #region Properties
        public HtmlCheckBox UIChkSelectAllCheckBox
        {
            get
            {
                if ((this.mUIChkSelectAllCheckBox == null))
                {
                    this.mUIChkSelectAllCheckBox = new HtmlCheckBox(this);
                    #region Search Criteria
                    this.mUIChkSelectAllCheckBox.SearchProperties[HtmlCheckBox.PropertyNames.Id] = "ohrmList_chkSelectAll";
                    this.mUIChkSelectAllCheckBox.SearchProperties[HtmlCheckBox.PropertyNames.Name] = "chkSelectAll";
                    this.mUIChkSelectAllCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.Value] = null;
                    this.mUIChkSelectAllCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.LabeledBy] = null;
                    this.mUIChkSelectAllCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.Title] = null;
                    this.mUIChkSelectAllCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.Class] = null;
                    this.mUIChkSelectAllCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.ControlDefinition] = "id=ohrmList_chkSelectAll value=\"\" type=c";
                    this.mUIChkSelectAllCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.TagInstance] = "12";
                    this.mUIChkSelectAllCheckBox.WindowTitles.Add("OrangeHRM");
                    #endregion
                }
                return this.mUIChkSelectAllCheckBox;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCheckBox mUIChkSelectAllCheckBox;
        #endregion
    }
}
